# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database:
  logs:

services:
  app:    
    container_name: app
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env